---
# Arquivo: provisioning/ansible/roles/headscale/tasks/main.yml

- name: Estruturação de pastas
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /opt/headscale
    - /opt/headscale/config
    - /opt/headscale/lib

- name: Copiando compose do repositório para OPT
  copy:
    src: "/opt/my-homelab/networking/headscale/docker-compose.yaml"
    dest: /opt/headscale/docker-compose.yaml

- name: Gerar o config.yaml usando o template Jinja2 e variáveis
  template:
    src: "/opt/my-homelab/networking/headscale/config.yaml.j2"
    dest: /opt/headscale/config/config.yaml
