version: '3.8'
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n_docker
    restart: always
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=https 
      - N8N_RUNNERS_ENABLED=true
      - NODE_ENV=production
      #Em caso de uso de webhook internos, coloque o DNS da sua VPN
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
      - N8N_SECURE_COOKIE=false
    ports:
      - "127.0.0.1:5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files
    networks:
      - ${NETWORK_NAME}

volumes:
  n8n_data:

networks:
  ${NETWORK_NAME}:
    external: true